sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - dev # build master branch only
before_install:
  - yarn global add hexo-cli
install:
  - yarn
script:
  - hexo generate # generate static files
  - hexo deploy